### ISSUE TITLE
Maximum file size error when uploading using script

### ISSUE THREAD

**Issue by joakimnyman** [SocksPls/Jirafeau#3]
When using the script to upload a file the maximum file size seems to be 2M. I can upload larger files using the web interface.

Reproduce:
Simply run the docker image and use the script to upload a file. I tested with two "fake" files:
`dd if=/dev/zero of=file.txt count=1024 bs=2048` 2M works

`dd if=/dev/zero of=file.txt count=1024 bs=2056` > 2M 
`Error while uploading.
Error 6 FIX ME: Your file exceeds the maximum authorized file size.`

**Comment by SocksPls** [comment]
The original jirafeau developer can probably do more than I can here, you should let him know at https://gitlab.com/mojo42/Jirafeau
